spring:
  cache:
    type: redis
  application:
    name: FisExcelProject
  jackson:
    serialization-inclusion: NON_EMPTY
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  tomcat:
    accesslog:
      enabled: true
      access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
      directory: tomcat
      suffix: ".log"
      prefix: "FisExcelProject_access"
    basedir: access
  servlet:
    contextPath:  /api/fis
  port: 8080

project:
  group: core
  team: content
  application: 'FisExcelProject'

endpoints:
  prometheus:
    enabled: true
management:
  security:
    flag: false
  health:
    jms:
      enabled: false
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
